### ISSUE TITLE
Use of "Identifier" and "Id" as distinct definitions confusing

### ISSUE THREAD

**Issue by ahwagner** [ga4gh/vr-schema#56]
The schema has several basic types that are used solely within other definitions. The use of "Identifier" and "Id" as types of distinct meaning is confusing. We should consider an alternative naming scheme for these basic, low-level concepts.

**Comment by reece** [comment]
This topic spawned months of debate and hand-wringing in VMC. @larrybabb and @rrfreimuth were primary proponents for this distinction and names. Like you, I initially opposed. The VMC spec briefly mentions somewhere that these names and meanings were chosen for parity with FHIR.

**Comment by ahwagner** [comment]
Okay, thank you for the clarification @reece. I will search for the rationale in the VMC spec and try to capture it here. I will withhold my reservations about these terms until after doing so.

**Comment by reece** [comment]
Comment is [here]( https://docs.google.com/document/d/12E8WbQlvfZWk5NrxwLytmympPby6vsv60RxCeD5wc1E/edit#bookmark=id.79yt1wijkvsa)

BTW, I am in favor of getting rid of the conceptual distinction (and therefore the dual names). The current trajectory is that every Identifier is a CURIE, and that CURIE prefixes SHOULD be from identifiers.org.

**Comment by ahwagner** [comment]
Perhaps this could be simplified by renaming the `Identifier` field to `ExtId` or `RefId` or similar? That said, I agree with @reece that we could also merge these fields, and treat `Id` as an instance of `Identifier` in the implementation namespace.

@rrfreimuth @larrybabb, your thoughts on renaming the `Identifier` type in schema and/or merging with `Id`?

**Comment by larrybabb** [comment]
Please consider reviewing the topic on id vs identifier in the HL7 FHIR spec. It's been well vetted and discussed for years and while I agree with the concerns and confusion, there is no magic answer as it is a difficult concept but very critical to both computational vs business utilization and practices with identity values.
See here. https://www.hl7.org/fhir/datatypes.html#identifier

**Comment by larrybabb** [comment]
Please consider reviewing the topic on id vs identifier in the HL7 FHIR spec. It's been well vetted and discussed for years and while I agree with the concerns and confusion, there is no magic answer as it is a difficult concept but very critical to both computational vs business utilization and practices with identity values.
See here. https://www.hl7.org/fhir/datatypes.html#identifier

**Comment by ahwagner** [comment]
Thanks for the link @larrybabb. I agree with the need for the `Identifier` field, my primary concern is the similarity in _name_ to `Id` (this is like having a system with distinct `user` and `usr` objects, whose distinctions are indiscernible from the object name to the observer). Given the FHIR summary description of `Identifier` (emphasis mine):
>A numeric or alphanumeric string that is associated with a single object or entity within a given system. *Typically, identifiers are used to connect content in resources to external content available in other frameworks or protocols.* Identifiers are associated with objects and may be changed or retired due to human or system process and errors.

Is it unreasonable to consider renaming this field in vr-schema to `ExtId` / `ExtIdentifier` / `FHIRIdentifier` / `BusinessId` / 'BID' / etc? It is not clear to me from the description in this section why the use of `Identifier` as the field name is critical–and if it is, I think we need to capture that. I don't mean to throw a wrench in the works at the 11th hour, but I'm trying to look at this the way the PRC would. Unencumbered with the months of debate that it took to reach this decision, and having (I believe) a good understanding of the computational vs business needs for maintaining these two distinct identifier objects, I would still prefer a name that speaks to the intent of the external (business) identifier field. 

In my view, there is no need for any other changes, but I'm not convinced that matching the object name to the related concept in FHIR is sufficient rationale for persisting this confusion. This is particularly true as the internal fields for [our identifier object](https://github.com/ga4gh/vr-schema/blob/master/schema/vr.yaml#L396-L412) are compatible with related [FHIR fields](https://www.hl7.org/fhir/datatypes.html#identifier) but do not share the same name (e.g. our `identifier.namespace` would map to FHIR `identifier.system`).

**Comment by rrfreimuth** [comment]
As mentioned, I support the idea of keeping an externally (relative to the document in which it is used) meaningful, namespaced `Identifier` separate from an internal (local to a document/message) `id` (or `Id`).  I'm not terribly concerned about the label used as the attributes' names, but think alignment with other more established standards (e.g., FHIR) would benefit the adopter community.

**Comment by reece** [comment]
I get it and you're right to bring it up.

I'm in a weird position because I've worked to minimize the differences so we'd obviate Id (using Identifiers in their place). Especially for a schema for exchange, the notion of an internal identifier is unnecessary.

However, I just can't predict off the cuff where this will hurt and I know that it's less important than existing showstoppers.

So, I'd really like to just put a pin in it as a nice-to-have for pre-1.0, then get back to the critical path stuff.

**Comment by reece** [comment]
I'm now in a place to comment on the impact of demucking the Id/Identifier confusion: We should do it for 1.0 and the effort is minimal.

In the current schema, we're really using the `Id` class as an identifier (in the inter-system identifier sense). So, I'd argue that we're even compelled to make this change for consistency.

Specific proposal:
* Drop the concept of an internal id entirely, and therefore the `Id` class. As a schema whose primary mission is to exchange data *between* systems, by definition there's nothing "internal". Implementations are likely to have internal ids, but they are not relevant to the schema.
* Clarify that an `Identifier`, consistent with HL7/FHIR as well as de facto bioinformatics uses, is a CURIE-formatted string that refers to objects. We RECOMMEND using namespaces (CURIE "prefixes") as defined at identifiers.org. We also define a new prefix, `ga4gh`, and propose a scheme for these.

@ahwagner @rrfreimuth @larrybabb : Agreed?

**Comment by reece** [comment]
Addendum: The above proposal does mean that consumers would be *required* to use CURIE-formatted identifiers. They would not be able to use arbitrary strings as identifiers.

Although I personally like that stand, I would be satisfied with relaxing Identifier to mean any string, and RECOMMEND CURIE-syntax.

The primary issue is whether VR really has an internal Id at all. I believe we do not and that we should remove it.

**Comment by ahwagner** [comment]
I'm fine with this, but I think that we want @rrfreimuth to sign off on it as well before making the change.

**Comment by larrybabb** [comment]
I don't want to stand in the way of progress. But I do think its worth clarifying the purpose of the id v identifier that FHIR uses in practice. 

The 'id' property is on EVERY Resource in FHIR. It is built into the top level DomainResource class from which all independently representable concepts are subclassed.

'identifier' is a separate data type with separate attributes for system (i.e. namespace) and value (i.e. unique id for that namespace) and a few others.

The 'identifier' is on many (maybe even most) Resources, but is not presumed to be the primary means for associating and linking shared concepts in messages.

HL7 FHIR is all about the sharing of data over the wire, the messaging. It is not meant to be a conceptual model or something that a physical database would use to define its structure.

In the FHIR messaging model, there is the need for a very flexible way to define 'id's for the 1-to-n instances of concepts/resources that are shared in a given message document. They intentionally did not want (nor should they have) placed a constraint on how and what that 'id' value should be. It is primarily and solely intended to be used to provide a value that is unique within the most narrow of contexts, a single message document itself.

It is confusing to folks because they often conflate the purpose of the 'id' on the concepts/resource instances in a message as having to be globally or universally unique and available to all.  While this is a really great aim it is too restrictive for the mere purpose of sharing a single message over a wire.

Our computed digest is absolutely aligned with the notion of a FHIR 'identifier'. Furthermore, in FHIR and I would presume any messaging model you can use an identifier or any value that suits the purposes of 'id'ing a given concept in the scope of the message.

The big question we need to answer is: do we care about addressing how folks would share VR concepts in the context of a larger scoped message whereby they may or may not want to use our computed 'identifier'. 

For example, if we ever do get HL7 FHIR to adopt the VR data types as 1st class types, will we strongly suggest, or require that the 'identifier' be included or will we say that they can wrap our data types in FHIR resources such that folks can have the flexibility to use FHIR 'id's when sharing VR data in FHIR messages, bundles, documents, etc..

We should take care to appreciate the pretty fundamental principles of FHIR's specification in this area so that we do not make decisions on misunderstanding the purpose.  'id' does not equal 'identifier' and we should take care to align ourselves with 'identifier' and the idea of 'id' is out of scope or not relevant to the scope of our specification.

**Comment by larrybabb** [comment]
i believe that decoupling the purpose of a message entity's id from it's contextual/business identifier is a pretty fundamental and smart design decision. I believe there's a strong engineering and design argument behind this in the core FHIR spec. Let's be careful to not couple these concerns so tightly in our spec that we end up trapped by this decision when the implementers need and want to use our work.

**Comment by ahwagner** [comment]
As the two people reviewing the spec in detail for documentation (but not having been involved in the construction of this component), @pnrobinson and I independently arrived at the same concern:

**`Id` and `Identifier` are similar names and thus confusing.**

Given that we're 2 for 2 on this point, and that this is intended to be a GA4GH spec (and adopted by groups with disparate objectives and needs around the world), if we are to keep both the `Id` and `Identifier` primitives, I *strongly* feel we should rename `Identifier` to `ExtId` or similar, but really need the group to concretely approve that approach. @rrfreimuth is [less (not?) concerned](https://github.com/ga4gh/vr-schema/issues/56#issuecomment-494866489) about changing the label of `Identifier` to something different. Naturally none of this is an issue if we end up dropping one of the two primitive types.

On that subject, dropping the `Id` primitive entirely and revising the `Identifier` to be a (recommended) CURIE makes perfect sense to me. After all, the whole notion of our `id` attributes (e.g. `Allele.id`, `Location.id`) are meant to capture the VR computed ID, and this is where the `Identifier` primitive is (proposed) to be used. If a system chooses to _overwrite_ these Ids with another string for use in internal messaging (such as @larrybabb [described](https://github.com/ga4gh/vr-schema/issues/56#issuecomment-497807105) for FHIR), it won't match computed identifiers of VR messages on other systems–but I can see the value of leaving the schema flexible for such purposes. We need to make a final call on this point ASAP.

**Comment by reece** [comment]
A riff on Alex's proposal:

* Object ids are type `Id`, which represented as a string. For the purpose of a message, an `Id` is an opaque string that acts as a key. VR imposes no constraints on a string. (This is exactly where VMC landed.)
* To improve exchange of information between systems, VR RECOMMENDS that implementations:
  * use (string) CURIEs as ids when generating and parsing messages
  * use namespaces registered at [identifiers.org](https://registry.identifiers.org/) (e.g., `refseq`, `ensembl`, `lrg`) be used as the CURIE `prefix` component. 
* use the VR computed id mechanism to generate globally distributed unique identifiers (w/link to section)

This proposal 1) eliminates the Id/Identifier confusion and 2) maximizes the flexibility of the schema to support implementations that want full control over the format of the id.

`Identifier` implies a structured identifier to me. I'd like to avoid that term for unstructured content.
